TYPO3:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Pixelbrackets.NonWord'
                '@controller': 'Login'
                '@action': 'login'
                '@format': 'html'