TYPO3:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'
            tokenClass: UsernamePasswordHttpBasic
